# Generated by Django 2.0.9 on 2018-12-15 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='registered_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
